name: Go CI/CD

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go Env
        uses: actions/setup-go@v2.1.3
        with:
            go-version: '1.15'
      - name: Go Version Check
        run: |
          go version
          
      - name: Install publish unit test
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        
      - name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
      - if: ${{ success }}
        name: Install Goblin
        run: |
          go get github.com/franela/goblin
      - if: ${{ success }}
        name: Test Goblin
        run: |
          go test ./fib -v | go2xunit >report.xml
      - if: ${{ success }}
