name: Go CI/CD

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go Env
        uses: actions/setup-go@v2.1.3
        with:
            go-version: '1.15'
      - name: Go Version Check
        run: |
          go version
      - name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
          go get github.com/franela/goblin
          go test -v
